import { useState } from "react";
import "../public/css/app.css"; // Updated path (assumes you placed your CSS in `src/app.css`)

function App() {
  const [allStudents] = useState([
    {
      roll_no: 89631,
      first_name: "Jay",
      last_name: "Pawar",
      age: 15,
      gender: "male",
      phone: "7863214591",
      address: "Surat",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89634,
      first_name: "Karan",
      last_name: "Pawar",
      age: 17,
      gender: "male",
      phone: "9110933585",
      address: "Rajkot",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89635,
      first_name: "Nisha",
      last_name: "Kapoor",
      age: 14,
      gender: "female",
      phone: "9510443465",
      address: "Ahmedabad",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89636,
      first_name: "Pooja",
      last_name: "Pawar",
      age: 16,
      gender: "female",
      phone: "9139954204",
      address: "Surat",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89637,
      first_name: "Nisha",
      last_name: "Yadav",
      age: 17,
      gender: "female",
      phone: "9838594583",
      address: "Ahmedabad",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89638,
      first_name: "Priya",
      last_name: "Joshi",
      age: 13,
      gender: "female",
      phone: "9708549984",
      address: "Ahmedabad",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89639,
      first_name: "Rahul",
      last_name: "Chopra",
      age: 16,
      gender: "male",
      phone: "9680897235",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89640,
      first_name: "Karan",
      last_name: "Joshi",
      age: 15,
      gender: "male",
      phone: "9431516191",
      address: "Ahmedabad",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89641,
      first_name: "Priya",
      last_name: "Joshi",
      age: 14,
      gender: "female",
      phone: "9156753853",
      address: "Ahmedabad",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89642,
      first_name: "Rahul",
      last_name: "Kapoor",
      age: 16,
      gender: "male",
      phone: "9509543588",
      address: "Rajkot",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89643,
      first_name: "Karan",
      last_name: "Chopra",
      age: 17,
      gender: "male",
      phone: "9312144779",
      address: "Vadodara",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89644,
      first_name: "Amit",
      last_name: "Joshi",
      age: 14,
      gender: "male",
      phone: "9806342982",
      address: "Surat",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89645,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 17,
      gender: "male",
      phone: "9113943184",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89647,
      first_name: "Priya",
      last_name: "Mehta",
      age: 14,
      gender: "female",
      phone: "9377322074",
      address: "Ahmedabad",
      class: "9th",
      division: "B",
    },
    {
      roll_no: 89648,
      first_name: "ysashvi",
      last_name: "Rathod",
      age: 16,
      gender: "female",
      phone: "9338138034",
      address: "Rajkot",
      class: "8th",
      division: "A",
    },
    {
      roll_no: 89649,
      first_name: "Jay",
      last_name: "Rathod",
      age: 17,
      gender: "male",
      phone: "9762941810",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89650,
      first_name: "Jay",
      last_name: "Pawar",
      age: 17,
      gender: "male",
      phone: "9681076930",
      address: "Vadodara",
      class: "9th",
      division: "A",
    },
    {
      roll_no: 89651,
      first_name: "Priya",
      last_name: "Verma",
      age: 13,
      gender: "female",
      phone: "9986571649",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89652,
      first_name: "Ravi",
      last_name: "Shah",
      age: 14,
      gender: "male",
      phone: "9128963052",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89653,
      first_name: "Vikas",
      last_name: "Rathod",
      age: 13,
      gender: "male",
      phone: "9412530266",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89660,
      first_name: "Ravi",
      last_name: "Mehta",
      age: 16,
      gender: "male",
      phone: "9253250072",
      address: "Surat",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89661,
      first_name: "Priya",
      last_name: "Mehta",
      age: 13,
      gender: "female",
      phone: "9972403305",
      address: "Surat",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89662,
      first_name: "Jay",
      last_name: "Joshi",
      age: 17,
      gender: "male",
      phone: "9521289893",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89663,
      first_name: "Vikas",
      last_name: "Shah",
      age: 15,
      gender: "female",
      phone: "9116504732",
      address: "Vadodara",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89664,
      first_name: "Sneha",
      last_name: "Verma",
      age: 13,
      gender: "female",
      phone: "9189031215",
      address: "Surat",
      class: "8th",
      division: "B",
    },
    {
      roll_no: 89665,
      first_name: "Jay",
      last_name: "Joshi",
      age: 14,
      gender: "male",
      phone: "9383800489",
      address: "Bharuch",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89666,
      first_name: "Rahul",
      last_name: "Yadav",
      age: 13,
      gender: "male",
      phone: "9468892099",
      address: "Vadodara",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89667,
      first_name: "Rahul",
      last_name: "Pawar",
      age: 16,
      gender: "male",
      phone: "9925938970",
      address: "Ahmedabad",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89705,
      first_name: "Pooja",
      last_name: "Rathod",
      age: 16,
      gender: "female",
      phone: "9931289155",
      address: "Surat",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89706,
      first_name: "Priya",
      last_name: "Chopra",
      age: 14,
      gender: "female",
      phone: "9103126278",
      address: "Rajkot",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89707,
      first_name: "Pooja",
      last_name: "Verma",
      age: 17,
      gender: "female",
      phone: "9158757783",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89708,
      first_name: "Priya",
      last_name: "Kapoor",
      age: 15,
      gender: "female",
      phone: "9149199948",
      address: "Vadodara",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89709,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 14,
      gender: "male",
      phone: "9775827600",
      address: "Rajkot",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89710,
      first_name: "Rahul",
      last_name: "Chopra",
      age: 17,
      gender: "male",
      phone: "9800978695",
      address: "Surat",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89711,
      first_name: "Amit",
      last_name: "Verma",
      age: 17,
      gender: "male",
      phone: "9774030913",
      address: "Surat",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89712,
      first_name: "Pooja",
      last_name: "Patel",
      age: 14,
      gender: "female",
      phone: "9960333116",
      address: "Ahmedabad",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89713,
      first_name: "Nisha",
      last_name: "Pawar",
      age: 14,
      gender: "female",
      phone: "9677795809",
      address: "Ahmedabad",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89714,
      first_name: "Jay",
      last_name: "Rathod",
      age: 16,
      gender: "male",
      phone: "9994849546",
      address: "Bharuch",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89715,
      first_name: "Amit",
      last_name: "Verma",
      age: 16,
      gender: "male",
      phone: "9129525413",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    // Add rest of the data...
  ]);

  return (
    <div className="container">
      <h1 className="title">📚 Students Table</h1>

      <div className="table-container">
        <table className="student-table">
          <thead>
            <tr>
              <th>No</th>
              <th>Roll No</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Age</th>
              <th>Gender</th>
              <th>Class</th>
              <th>Division</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {allStudents.map((stud, index) => (
              <tr key={stud.roll_no}>
                <td>{index + 1}</td>
                <td>{stud.roll_no}</td>
                <td>{stud.first_name}</td>
                <td>{stud.last_name}</td>
                <td>{stud.age}</td>
                <td>{stud.gender}</td>
                <td>{stud.class}</td>
                <td>{stud.division}</td>
                <td>{stud.phone}</td>
                <td>{stud.address}</td>
                <td>
                  <button className="bg-danger">del</button> 
                  
                  <button className="bg-danger">edit</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default App;
